name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4,16 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Should build?
        id: should_build
        shell: bash
        run: |
          source build.conf
          source utils.sh

          is_patches_latest() {
            declare -r last_patches_url=$(wget -nv -O- https://api.github.com/repos/inotia00/revanced-patches/releases/latest | tr -d ' ' | sed -n 's/.*"browser_download_url":"\(.*jar\)".*/\1/p')
            declare -r last_patches=${last_patches_url##*/}
            cur_patches=revanced-patches-$(sed -n 's/.*Patches: \(.*\)/\1/p' latest_build_ex.md | sed -e 's/([^()]*)//g'  | xargs).jar

            echo "current patches version: $cur_patches"
            echo "latest patches version: $last_patches"
            [ "$cur_patches" != "$last_patches" ] # test success=>build, fail=>dont build
          }

          if ! git checkout update; then
            echo "first time building!"
            echo "SHOULD_BUILD=1"  >> $GITHUB_OUTPUT
          elif is_patches_latest || is_youtube_latest; then
            echo "build!"
            echo "SHOULD_BUILD=1"  >> $GITHUB_OUTPUT
          else
            echo "dont build!"
            echo "SHOULD_BUILD=0"  >> $GITHUB_OUTPUT
          fi

    outputs:
      SHOULD_BUILD: ${{ steps.should_build.outputs.SHOULD_BUILD }}

  build:
    needs: check
    uses: ./.github/workflows/build.yml
    if: ${{ needs.check.outputs.SHOULD_BUILD == 1 }}
  deletele-action_log:

    uses: ./.github/workflows/del.yml

  deletele-release_log:

    uses: ./.github/workflows/del-release.yml

